"""Render a :class:`Fleet` into the shared index artifacts.

Two outputs, both regenerable (never hand-edited):
  - ``registry.json`` — structured source of truth
  - ``PROJECTS.md``   — human/agent index with per-family tables + Mermaid graph
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from fleetman.models import Fleet

_FAM_ORDER = ["template", "dantic", "man", "nix", "nvim", "other"]
_FAM_TITLE = {
    "template": "Templates / scaffolding",
    "dantic": "`*dantic` libraries",
    "man": "`*man` manager tools",
    "nix": "Nix / NixOS infrastructure",
    "nvim": "Neovim plugins",
    "other": "Other libraries & apps",
}


def _sid(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", s)


def registry_json(fleet: Fleet) -> str:
    payload = {
        "generated_by": fleet.generated_by,
        "root": fleet.root,
        "project_count": len(fleet.projects),
        "projects": [p.model_dump() for p in fleet.projects],
    }
    return json.dumps(payload, indent=2) + "\n"


def projects_md(fleet: Fleet) -> str:
    projects = fleet.projects
    py_edges = fleet.python_edges()
    nix_edges = fleet.nix_edges()
    counts = {k: sum(p.kind == k for p in projects) for k in ("python", "nix", "nvim", "other")}

    out: list[str] = []
    out.append("# PROJECTS")
    out.append("")
    out.append("> Generated by `fleetman index` — do not hand-edit. "
               "Re-run to refresh. See `../../AGENTS.md` for conventions.")
    out.append("")
    out.append(f"**{len(projects)}** projects "
               f"({counts['python']} python, {counts['nix']} nix, "
               f"{counts['nvim']} nvim, {counts['other']} other) · "
               f"**{len(py_edges) + len(nix_edges)}** internal edges "
               f"({len(py_edges)} python, {len(nix_edges)} nix) · "
               f"**{sum(p.stub for p in projects)}** uncustomized scaffolds.")
    out.append("")

    ranked = sorted(projects, key=lambda p: len(p.dependents), reverse=True)
    top = [p for p in ranked if p.dependents][:8]
    if top:
        out.append("## Most depended-on")
        out.append("")
        for p in top:
            out.append(f"- **{p.name}** ← {len(p.dependents)} ({', '.join(p.dependents)})")
        out.append("")

    out.append("## Projects by family")
    out.append("")
    for fam in _FAM_ORDER:
        members = sorted((p for p in projects if p.family == fam), key=lambda p: p.name.lower())
        if not members:
            continue
        out.append(f"### {_FAM_TITLE[fam]} ({len(members)})")
        out.append("")
        out.append("| Project | Layer | Purpose | Depends on |")
        out.append("|---|---|---|---|")
        for p in members:
            if p.stub:
                purpose = "⚠ uncustomized template-py scaffold"
            else:
                purpose = p.purpose.replace("|", "\\|") or "—"
                if len(purpose) > 120:
                    purpose = purpose[:117] + "…"
            alldeps = p.depends_on + [f"{d} (nix)" for d in p.flake_inputs]
            out.append(f"| {p.name} | {p.layer} | {purpose} | {', '.join(alldeps) or '—'} |")
        out.append("")

    out.append("## Internal dependency graph")
    out.append("")
    if py_edges or nix_edges:
        out.append("Solid arrow = python dependency (`pyproject.toml`); "
                   "dashed = nix flake input (`flake.nix`).")
        out.append("")
        out.append("```mermaid")
        out.append("graph LR")
        connected = {n for e in (*py_edges, *nix_edges) for n in e}
        for p in sorted(connected):
            out.append(f'  {_sid(p)}["{p}"]')
        for src, dst in sorted(py_edges):
            out.append(f"  {_sid(src)} --> {_sid(dst)}")
        for src, dst in sorted(nix_edges):
            out.append(f"  {_sid(src)} -.-> {_sid(dst)}")
        out.append("```")
    else:
        out.append("_No internal edges detected._")
    out.append("")
    return "\n".join(out)


def write_index(fleet: Fleet, out_dir: Path) -> list[Path]:
    """Write both artifacts into ``out_dir`` (created if needed)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    reg, md = out_dir / "registry.json", out_dir / "PROJECTS.md"
    reg.write_text(registry_json(fleet))
    md.write_text(projects_md(fleet))
    return [reg, md]
